//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid idBook { get; set; }
        public System.Guid idUser { get; set; }
        public string comment1 { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.Guid id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
